#SPDX-License-Identifier: MIT-0
---
# handlers file for post-install
- name: restart service ntp agent on ubuntu
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"
