---        
- name: DBserver setup 
  hosts: dbservers
  become: yes
    #vars: 
    #db_name: electric
    #dbuser: current
    #dbpass: tesla
  
  tasks: 
    - debug:
        msg: "The dbname is {{db_name}}"

    - debug:
        var: dbuser

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install mariadb-server
      ansible.builtin.apt:
        name: mariadb-server
        state: present
    
    - name: Install pymysql
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: start mariadb service 
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes 

    - name: Create a new database with name 'accounts'
      mysql_db:
        name: "{{db_name}}"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create database user with vars with all database privileges
      mysql_user:
        name: "{{db_name}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      register: dbout

    - name: print dbout variable
      debug: 
        var: dbout  
