---
- name: Webserver setup
  hosts: webservers
  become: yes
  tasks: 
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: start apache2 service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
        
- name: DBserver setup 
  hosts: dbservers
  become: yes
  tasks: 
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install mariadb-server
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: start mariadb service 
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes 

